on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    name: macOS (Xcode ${{ matrix.xcode }})
    strategy:
      matrix:
        xcode: ['16.3']
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Run tests
        run: swift test

      - name: Build CLI release binary
        run: swift build -c release --product open-music-event

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-music-event-macos
          path: .build/release/open-music-event

  linux:
    name: Linux (Swift ${{ matrix.swift }})
    strategy:
      matrix:
        swift:
          - '6.0'
          - '6.1'
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4

      - name: Install SQLite
        run: apt update && apt -y install libsqlite3-dev

      - name: Build CLI release binary
        run: swift build -c release --product open-music-event

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-music-event-linux-${{ matrix.swift }}
          path: .build/release/open-music-event
