on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core-linux:
    name: Core (Linux)
    strategy:
      matrix:
        swift: [ '6.1' ]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4

      - name: Install SQLite
        run: apt update && apt -y install libsqlite3-dev

      - name: Run Core Tests
        run: |
          cd Core
          swift test --enable-test-discovery --parallel
